name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - { name: '3.10', python: '3.10', os: ubuntu-latest, tox: py310, mongodb: '4.4', redis: '6' }
          - { name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39, mongodb: '4.4', redis: '6' }
          - { name: '3.8', python: '3.8', os: ubuntu-latest, tox: py38, mongodb: '4.4', redis: '6' }
          - { name: '3.7', python: '3.7', os: ubuntu-latest, tox: py37, mongodb: '4.4', redis-version: '6' }
          - { name: 'PyPy', python: 'pypy-3.7', os: ubuntu-latest, tox: pypy37, mongodb: '4.4', redis: '6' }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
      - uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis }}
      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions
      - name: Start mongo ${{ matrix.mongodb-version }}
        run: |
          mongo eve_test --eval 'db.createUser({user:"test_user", pwd:"test_pw", roles:["readWrite"]});'
      - name: Run tox targets for ${{ matrix.python }}
        run: tox -e ${{ matrix.tox }}

  aarch64_tests:
    name: aarch64-${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - { name: 'cp310-cp310', python: '3.10', os: ubuntu-latest, tox: py310, mongodb: '4.4', redis: '6' }
          - { name: 'cp39-cp39', python: '3.9', os: ubuntu-latest, tox: py39, mongodb: '4.4', redis: '6' }
          - { name: 'cp38-cp38', python: '3.8', os: ubuntu-latest, tox: py38, mongodb: '4.4', redis: '6' }
          - { name: 'cp37-cp37', python: '3.7', os: ubuntu-latest, tox: py37, mongodb: '4.4', redis-version: '6' }
    env:
      py: /opt/python/${{ matrix.name }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1          
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
      - uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis }}
      - name: Install dependencies
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          set -xe && \
          python -VV && \
          python -m site && \
          python -m pip install --upgrade pip setuptools wheel && \
          python -m pip install --upgrade virtualenv tox tox-gh-actions && \
          mongo eve_test --eval "db.createUser({user:"test_user", pwd:"test_pw", roles:["readWrite"]});" && \
          tox -e ${{ matrix.tox }} && \
          deactivate'
